### ISSUE TITLE
Parse path from full svg file

### ISSUE THREAD

**Issue by erf** [dnfield/flutter_path_drawing#22]
Have you considered allowing passing a full `svg` file (and not just the path data `d`) ? 

Or did you consciously leave out the `xml` parsing for a higher level packages?

Perhaps `flutter_svg` could have a helper method to parse a `path` from a full `svg` (as i was missing that right now).

**Comment by dnfield** [comment]
flutter_svg exports an SVG parser. Parsing an individual path is a bit harder than it sounds, because you have to support styling and attribute inheritence. Unfortunately, the spec also allows SVG path elements to have attributes/styling that doesn't even make sense to me.

It should be trivial to write something that parses a list of paths, but if you're not going to support SVG you might as well not use XML either. And if you're not going to use XML you might as well encode your path data to something even more efficient that can be unpacked from `ByteData` :)

**Comment by erf** [comment]
I'm already using `flutter_path_drawing` to parse `svg` to a flutter `path`, i just thought it would be more convenient to parse a `svg` directly. I see that there are more attributes there, and it would perhaps be wrong to just ignore those for just parsing the `path d` data. It would however be awesome if the path could be transformed based on the `svg` data.

Let me explain what i'm trying to do.. I'm using the [flutter_confetti](https://github.com/funwithflutter/flutter_confetti) package and i would like to create some confetti particles paths based off premade svg's (as they are a pretty common file format). I do however notice now that some of the svg models are scaled differently and not sure how i can scale them so that they are in the same scale. I guess there is a relation between the svg ViewBox / Width / Height and the individual path data points.. I guess i could use the path.bounds and scale them based on the prev mentioned svg elements / attrributes.

**Comment by erf** [comment]
I was able to parse it using the `xml` package (and was able to scale the paths based on their bounds). Closing as i see the points on keeping it simple and not having to parse all the svg attributes.
