### ISSUE TITLE
Separating parsing and drawing into different packages

### ISSUE THREAD

**Issue by aloisdeniel** [dnfield/flutter_path_drawing#3]
I'm currently trying to make a built tool that generate code based on parsed path, but I'm stucked since this package depend on flutter SDK.

I think that it would be better to split the project into two different packages :

* **path_parsing** : only the parsing logic (`SvgPathStringSource`,  ...).
* **path_drawing** : takes the result of a parsed tree and emits path commands.

For a really generic package, this implies removing all UI apis. I already did the job by relying only on `dart:math` (basically replacing `Offset` by `Point`, and removing all `Path`call to return segments instead) : [gist](https://gist.github.com/aloisdeniel/fe6c50397f6278be59231d35997ad8f9)

The `SvgPathNormalizer`could also be kept into **path_parsing** by changing its method signature and creating normalized `PathSegmentData`  :

```dart
  PathSegmentData emitSegment(PathSegmentData segment);
```

A new `SvgPathBuilder`class could be then used from **path_drawing** :

```dart
class SvgPathBuilder {
 void emitSegment(PathSegmentData normalizedSegment, Path path) {
     // ...
  }
}
```

This would allow more flexibility. What do you think ?

**Comment by dnfield** [comment]
Is the goal here to just have a package that doesn't depend on flutter?

I'm not clear on how this will help things vs. splitting out the classes/methods.

**Comment by aloisdeniel** [comment]
Yes, because build tools are running on the dart VM and can't depend on Flutter or 'dart:ui'.

I currently use the code posted above for code generation.

**Comment by dnfield** [comment]
I like this idea.  I'm not sure how much time I'll have to work on it in the near term, but would be happy to take a PR for it.  Otherwise I'll look into it over the next few weeks.

**Comment by dnfield** [comment]
Hmm yes.  Give me a little time and I'll get repos set up

**Comment by dnfield** [comment]
https://github.com/dnfield/dart_path_parsing

and a3172e6 now consumes it here

Tried to keep the interface pretty simple only for normalized paths with `PathProxy`, but should still be possible to get full `PathSegmentData` (just would require more code to do so).  I'd prefer to keep it this way, since the actual use cases for right now (dynamic parsing of SVG path data at runtime, preparing built value type Paths/SVGs at compile time) will want the normalized versions anyway.

I'll take a crack at some of the generation we've been discussing - I'm particularly interested in doing it for SVG, as currently parsing the SVG data takes a significant amount of time in the overall pipeline.  I had been thinking it'd be nice to go to a flat buffer type format, but I think this might be more useful (at the loss of dynamically loading vector data) for now, and more performant at runtime.

**Comment by aloisdeniel** [comment]
Great thank you! 👍
